version: "3"

services:
  database:
    container_name: sf_postgres_local
    image: postgres:16.2-alpine3.19
    shm_size: 1g
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sf
      POSTGRES_PASSWORD: 123456
    volumes:
      - sf_postgres_data:/var/lib/postgresql/data
    networks:
      - sf

networks:
  sf:
volumes:
  sf_postgres_data:
